# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowServer(object):
    def setupUi(self, MainWindowServer):
        MainWindowServer.setObjectName("MainWindowServer")
        MainWindowServer.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindowServer)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.portLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.portLabel.setFont(font)
        self.portLabel.setObjectName("portLabel")
        self.gridLayout_2.addWidget(self.portLabel, 0, 0, 1, 1)
        self.portInput = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.portInput.setFont(font)
        self.portInput.setObjectName("portInput")
        self.gridLayout_2.addWidget(self.portInput, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.stopButton.setFont(font)
        self.stopButton.setObjectName("stopButton")
        self.gridLayout.addWidget(self.stopButton, 1, 0, 1, 1)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.startButton.setFont(font)
        self.startButton.setObjectName("startButton")
        self.gridLayout.addWidget(self.startButton, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.logOutput = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.logOutput.setFont(font)
        self.logOutput.setReadOnly(True)
        self.logOutput.setObjectName("logOutput")
        self.gridLayout_3.addWidget(self.logOutput, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        MainWindowServer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowServer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindowServer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowServer)
        self.statusbar.setObjectName("statusbar")
        MainWindowServer.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowServer)
        QtCore.QMetaObject.connectSlotsByName(MainWindowServer)

    def retranslateUi(self, MainWindowServer):
        _translate = QtCore.QCoreApplication.translate
        MainWindowServer.setWindowTitle(_translate("MainWindowServer", "Server"))
        self.portLabel.setText(_translate("MainWindowServer", "Port:"))
        self.portInput.setText(_translate("MainWindowServer", "8000"))
        self.stopButton.setText(_translate("MainWindowServer", "Stop Server"))
        self.startButton.setText(_translate("MainWindowServer", "Start Server"))
        self.logOutput.setHtml(_translate("MainWindowServer", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p></body></html>"))
